name: Build App

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: clippy
    - name: Check with Clippy
      run: cargo clippy -- -D warnings
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build
        args: --verbose